<a href="https://colab.research.google.com/github/sultanbst123/Hugging-Face-indo/blob/main/GPT_2_FT_ID.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<h1> GPT-2 FINE TUNE ID

Fine tune GPT-2 dengan data puisi Indonesia

## Library & File

Load id_puisi dari dataset hugging face

In [ ]:
!pip install datasets transformers[sentencepiece]

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 365 kB 32.4 MB/s 
     |████████████████████████████████| 4.7 MB 63.5 MB/s 
     |████████████████████████████████| 212 kB 72.1 MB/s 
     |████████████████████████████████| 115 kB 68.6 MB/s 
     |████████████████████████████████| 120 kB 73.8 MB/s 
     |████████████████████████████████| 127 kB 69.6 MB/s 
     |████████████████████████████████| 6.6 MB 62.5 MB/s 
     |████████████████████████████████| 1.3 MB 66.4 MB/s 
  Attempting uninstall: urllib3
    Found existing installation: urllib3 1.24.3
    Uninstalling urllib3-1.24.3:
      Successfully uninstalled urllib3-1.24.3


In [ ]:
import random
import numpy as np

# untuk mengambil datasetnya 
from datasets import load_dataset

In [ ]:
dataset = load_dataset("id_puisi", split="train")

Generating train split:   0%|          | 0/7223 [00:00<?, ? examples/s]

Dataset id_puisi downloaded and prepared to /root/.cache/huggingface/datasets/id_puisi/default/0.0.0/250d37fdf54c8f6967e73267d3c9c6410a48be89e8fb645d90a90c44959ef9a6. Subsequent calls will reuse this data.


In [ ]:
# random puisi
r = random.randint(0,len(dataset)) 

for key in dataset[r]:
    print(f"{key.upper()}: {dataset[r][key][:200]}\n")

TITLE: DUKA CINTA

AUTHOR: Oleh Gatra Aksara

PUISI: Cinta,.. 
 Jangan bersedih 
 Usap air mata di pipimu 
 Usah kamu meratapi kecewaku 
  
 Biar aku rasakan 
 Sendiri dengan ikhlas 
 Sesal yang menghantam dada 
 Agar engkau tiada luka karenanya 
  
 Te

PUISI_WITH_HEADER: DUKA CINTA 
 Oleh Gatra Aksara 
  
 Cinta,.. 
 Jangan bersedih 
 Usap air mata di pipimu 
 Usah kamu meratapi kecewaku 
  
 Biar aku rasakan 
 Sendiri dengan ikhlas 
 Sesal yang menghantam dada 
 Agar



In [ ]:
# check dataset info
dataset

Dataset({
    features: ['title', 'author', 'puisi', 'puisi_with_header'],
    num_rows: 7223
})

In [ ]:
dataset["puisi_with_header"][2]

'KAU \n Oleh Nur Rahma Utami \n Kau adalah separuh hidup ku \n Hanya kepadamu aku berbagi \n Kaulah yang mengajariku atri seorang sahabat \n Kau selalu ada untukku \n Saat aku sedih kau hadir menghiburku \n Saat aku menangis kau menghapuskan air mataku \n Saat aku terjatuh kau membantuku untuk bangkit \n Kau genggam kedua tanganku saat aku merasa takut \n Kaulah yang sangat berarti dalam hidupku \n Kau tak kan pernah terlupakan \n Kaulah sahabat pertamaku \n Senyumanmu yang kan selalu menghiasi hari-harikuSELAMANYAA... \n Kaulah Diana \n  \n '

## Pre processing data

Conrvert datasets to dataframe to concat title & puisi, then convert to datasets

In [ ]:
import pandas as pd 
from datasets import Dataset

In [ ]:

# first take value

df = dict()
df["title"] = dataset["title"][:]
df["puisi"] = dataset["puisi"][:]

In [ ]:
# convert to dataframe 

dataf = pd.DataFrame(df)

In [ ]:
dataf

title                                              puisi
0          UNTUK KEKASIHKU  Tiada lagi resah di hatiku \n Tiada lagi kerag...
1                    HUJAN  Gemericik senandung luluh merayu hati, \n Terj...
2                      KAU  Kau adalah separuh hidup ku \n Hanya kepadamu ...
3              TEPERANGKAP  Mungkin kau membiarkan aku \n Membiarkan peras...
4                      IBU  Ibu.. \n Kau adalah mutiara hatiku \n Mutiara ...
...                    ...                                                ...
7218  BUKAN PILIHAN HATIMU  Rasa kangen ini \n Tak pernah terharap sedikit...
7219                 TANYA  Dititik manakah aku berada,. \n Dalam jiwamu h...
7220                  AYAH  Semoga apa yang kau inginkanakan terjadi dimas...
7221  SAHABAT YANG TERLUKA  Sahabat..... \n Maafkan aku Setelah Di sekolah...
7222     BUNDAKU TERSAYANG  Ibu. \n Pengorbananmu adalah suatu cerminan ba...

[7223 rows x 2 columns]

In [ ]:
# concat title & puisi

In [ ]:
dataf["puisi_with_title"] = dataf["title"] + " \n " + dataf["puisi"]

In [ ]:
dataf # check

title                                              puisi  \
0          UNTUK KEKASIHKU  Tiada lagi resah di hatiku \n Tiada lagi kerag...   
1                    HUJAN  Gemericik senandung luluh merayu hati, \n Terj...   
2                      KAU  Kau adalah separuh hidup ku \n Hanya kepadamu ...   
3              TEPERANGKAP  Mungkin kau membiarkan aku \n Membiarkan peras...   
4                      IBU  Ibu.. \n Kau adalah mutiara hatiku \n Mutiara ...   
...                    ...                                                ...   
7218  BUKAN PILIHAN HATIMU  Rasa kangen ini \n Tak pernah terharap sedikit...   
7219                 TANYA  Dititik manakah aku berada,. \n Dalam jiwamu h...   
7220                  AYAH  Semoga apa yang kau inginkanakan terjadi dimas...   
7221  SAHABAT YANG TERLUKA  Sahabat..... \n Maafkan aku Setelah Di sekolah...   
7222     BUNDAKU TERSAYANG  Ibu. \n Pengorbananmu adalah suatu cerminan ba...   

                                       puisi_with_title  
0     UNTUK KEKASIHKU \n Tiada lagi resah di hatiku ...  
1     HUJAN \n Gemericik senandung luluh merayu hati...  
2     KAU \n Kau adalah separuh hidup ku \n Hanya ke...  
3     TEPERANGKAP \n Mungkin kau membiarkan aku \n M...  
4     IBU \n Ibu.. \n Kau adalah mutiara hatiku \n M...  
...                                                 ...  
7218  BUKAN PILIHAN HATIMU \n Rasa kangen ini \n Tak...  
7219  TANYA \n Dititik manakah aku berada,. \n Dalam...  
7220  AYAH \n Semoga apa yang kau inginkanakan terja...  
7221  SAHABAT YANG TERLUKA \n Sahabat..... \n Maafka...  
7222  BUNDAKU TERSAYANG \n Ibu. \n Pengorbananmu ada...  

[7223 rows x 3 columns]

In [ ]:
#convert to dataset

new_data = Dataset.from_pandas(dataf)

In [ ]:
new_data # check
display(new_data["puisi_with_title"][1])

'HUJAN \n Gemericik senandung luluh merayu hati, \n Terjamah larutan mensiasati. \n  \n Terus menyabani hingga rengkarnasi. \n Putih sejuk teramat berarti. \n Senantiasa menanti keputusan Tuhan kapan ia akan pergi. \n  \n Bila sampai waktu nya, \n Tetes demi tetes kian mengurai \xa0awan. \n Gemuruh kilat pelepas ikatan. \n Melepas hasrat bercinta tak terhelakan, \n Rayuan pulang tak hiraukan. \n Merintih seduh sedan tiada guna. \n  \n Hingga hujan mengiklaskan semua \n Demi senyuman yang menghianatinya, \n Yang tak terima akan kehadirannya \n Tanpa menyadari ia pantas untuk jatuh. \n  \n Jambi, 5 Mei 2017 \n  \n '

In [ ]:
# nice

## Define tokenizer

Tokenizer dengan ByteLevelBPETokenizer

In [ ]:
pip install tokenizers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [ ]:

# original
from tokenizers import ByteLevelBPETokenizer

# untuk manipulasi tokenizer
from tokenizers.implementations import ByteLevelBPETokenizer
from tokenizers.processors import BertProcessing

In [ ]:
# config params for tokenizer 

vc = 35000 # num vocab size
max_len = 256 # num max length of token

In [ ]:

# Instantiate tokenizer
tokenizer = ByteLevelBPETokenizer()

def batch_iterator(batch_size=1000):
    for i in range(0, len(new_data), batch_size):
        yield new_data[i: i + batch_size]["puisi_with_title"]

# Customized training
tokenizer.train_from_iterator(batch_iterator(), vc, min_frequency=2, special_tokens=[
    "<s>",
    "<pad>",
    "</s>",
    "<unk>",
    "<mask>",
])

In [ ]:
# Save files to disk
!mkdir GPT-2-puisi 
tokenizer.save_model("GPT-2-puisi")

['GPT-2-puisi/vocab.json', 'GPT-2-puisi/merges.txt']

In [ ]:

# contoh penggunaan nya 

tokenizer = ByteLevelBPETokenizer(
    "./GPT-2-puisi/vocab.json",
    "./GPT-2-puisi/merges.txt",
)

In [ ]:
tokenizer._tokenizer.post_processor = BertProcessing(
    ("</s>", tokenizer.token_to_id("</s>")),
    ("<s>", tokenizer.token_to_id("<s>")),
)

tokenizer.enable_truncation(max_length=max_len)

In [ ]:

# coba 

tokenizer.encode("saya punya orang yang nama nya siapa", "kenapa tidak tau kemana lagi").tokens

['<s>',
 's',
 'aya',
 'Ġpunya',
 'Ġorang',
 'Ġyang',
 'Ġnama',
 'Ġnya',
 'Ġsiapa',
 '</s>',
 'kenapa',
 'Ġtidak',
 'Ġtau',
 'Ġkemana',
 'Ġlagi',
 '</s>']

In [ ]:
tokenizer # before tokenizer fast

Tokenizer(vocabulary_size=35000, model=ByteLevelBPE, add_prefix_space=False, lowercase=False, dropout=None, unicode_normalizer=None, continuing_subword_prefix=None, end_of_word_suffix=None, trim_offsets=False)

In [ ]:

#teruskan ke tokenizerfast

from transformers import GPT2TokenizerFast

tokenizer = GPT2TokenizerFast.from_pretrained("./GPT-2-puisi", max_len=max_len)

Special tokens have been added in the vocabulary, make sure the associated word embeddings are fine-tuned or trained.


In [ ]:
tokenizer # after tokenizer fast

PreTrainedTokenizerFast(name_or_path='./GPT-2-puisi', vocab_size=35000, model_max_len=256, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'bos_token': AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=True), 'eos_token': AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=True), 'unk_token': AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=True)})

## Encode Data
Encode data to token with max_length 256

In [ ]:

# karena belum di split, saya akan split 5%:95%

raw_data = new_data.train_test_split(test_size=0.05)

In [ ]:
raw_data

DatasetDict({
    train: Dataset({
        features: ['title', 'puisi', 'puisi_with_title'],
        num_rows: 6861
    })
    test: Dataset({
        features: ['title', 'puisi', 'puisi_with_title'],
        num_rows: 362
    })
})

In [ ]:
# coba encode raw data 

outputs = tokenizer(
    raw_data["train"][:7]["puisi_with_title"],
    truncation = True,
    max_length = max_len, 
    return_overflowing_tokens = True,
    return_length = True,
)

print(f"Input IDs length: {len(outputs['input_ids'])}") # total baris
print(f"Input chunk lengths: {(outputs['length'])}") # total panjang kata
print(f"Chunk mapping: {outputs['overflow_to_sample_mapping']}") # chunk

Input IDs length: 7
Input chunk lengths: [107, 62, 122, 109, 150, 80, 96]
Chunk mapping: [0, 1, 2, 3, 4, 5, 6]


In [ ]:
outputs.keys()

dict_keys(['input_ids', 'attention_mask', 'length', 'overflow_to_sample_mapping'])

In [ ]:

# sekarang encode text nya 

def tokenize(element):
    outputs = tokenizer(
        element["puisi_with_title"],
        truncation = True,
        max_length = max_len,
        return_overflowing_tokens = True,
        return_length = True,
    )
    input_batch = []
    for input_ids in outputs["input_ids"]:
        input_batch.append(input_ids)
    return {"input_ids": input_batch}

In [ ]:
tokenized_datasets = raw_data.map(
    tokenize, batched=True, remove_columns=raw_data["train"].column_names
)
tokenized_datasets

  0%|          | 0/7 [00:00<?, ?ba/s]

  0%|          | 0/1 [00:00<?, ?ba/s]

DatasetDict({
    train: Dataset({
        features: ['input_ids'],
        num_rows: 7312
    })
    test: Dataset({
        features: ['input_ids'],
        num_rows: 385
    })
})

In [ ]:
7324*256 # total 1.874.944 token

1874944

In [ ]:
from transformers import DataCollatorForLanguageModeling

tokenizer.pad_token = tokenizer.eos_token # buat padding nya dengan eos_token

# untuk menyamakan semua I/O nya 

data_collator = DataCollatorForLanguageModeling(tokenizer, mlm=False, return_tensors="tf")

In [ ]:
tokenizer # after add pad token

PreTrainedTokenizerFast(name_or_path='./GPT-2-puisi', vocab_size=35000, model_max_len=256, is_fast=True, padding_side='right', truncation_side='right', special_tokens={'bos_token': AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=True), 'eos_token': AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=True), 'unk_token': AddedToken("<|endoftext|>", rstrip=False, lstrip=False, single_word=False, normalized=True), 'pad_token': '<|endoftext|>'})

In [ ]:

# coba dulu

out = data_collator([tokenized_datasets["train"][i] for i in range(100)])
for key in out:
    print(f"{key} shape: {out[key].shape}")

input_ids shape: (100, 256)
attention_mask shape: (100, 256)
labels shape: (100, 256)


In [ ]:
out # check tensor

{'input_ids': <tf.Tensor: shape=(100, 256), dtype=int32, numpy=
array([[ 4088,  6825,   262, ..., 35000, 35000, 35000],
       [ 2160, 10355,   262, ..., 35000, 35000, 35000],
       [27712,  6183,   262, ..., 35000, 35000, 35000],
       ...,
       [ 1208, 10362,  1670, ..., 35000, 35000, 35000],
       [10813,  6556,    41, ..., 35000, 35000, 35000],
       [19053,  7440,  1832, ..., 35000, 35000, 35000]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(100, 256), dtype=int32, numpy=
array([[1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       ...,
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0],
       [1, 1, 1, ..., 0, 0, 0]], dtype=int32)>, 'labels': <tf.Tensor: shape=(100, 256), dtype=int32, numpy=
array([[ 4088,  6825,   262, ...,  -100,  -100,  -100],
       [ 2160, 10355,   262, ...,  -100,  -100,  -100],
       [27712,  6183,   262, ...,  -100,  -100,  -100],
       ...,
       [ 1208, 10362,  1670, ...,  -100,  -1

In [ ]:

# masukan ke tf.dataset

tf_train_dataset = tokenized_datasets["train"].to_tf_dataset(
    columns=["input_ids", "attention_mask", "labels"],
    collate_fn=data_collator,
    shuffle=True,
    batch_size=8,
)
tf_eval_dataset = tokenized_datasets["test"].to_tf_dataset(
    columns=["input_ids", "attention_mask", "labels"],
    collate_fn=data_collator,
    shuffle=False,
    batch_size=8,
)

In [ ]:
tf_train_dataset, tf_eval_dataset

(<PrefetchDataset element_spec={'input_ids': TensorSpec(shape=(None, None), dtype=tf.int64, name=None), 'attention_mask': TensorSpec(shape=(None, None), dtype=tf.int64, name=None), 'labels': TensorSpec(shape=(None, None), dtype=tf.int64, name=None)}>,
 <PrefetchDataset element_spec={'input_ids': TensorSpec(shape=(None, None), dtype=tf.int64, name=None), 'attention_mask': TensorSpec(shape=(None, None), dtype=tf.int64, name=None), 'labels': TensorSpec(shape=(None, None), dtype=tf.int64, name=None)}>)

## Define model
GPT-2

In [ ]:
from transformers import GPT2Config, TFGPT2LMHeadModel

In [ ]:
# gunakan config GPT-2, lalu
# ubah vocab size dan params lain nya
# kalau ingin fine tune silahkan 

config = GPT2Config.from_pretrained(
    "gpt2", 
    vocab_size = vc, 
    n_ctx = max_len,
    bos_token_id = tokenizer.bos_token_id,
    eos_token_id = tokenizer.eos_token_id,
)

In [ ]:
config#.task_specific_params['text-generation']['max_length'] # check config

GPT2Config {
  "activation_function": "gelu_new",
  "architectures": [
    "GPT2LMHeadModel"
  ],
  "attn_pdrop": 0.1,
  "bos_token_id": 35000,
  "embd_pdrop": 0.1,
  "eos_token_id": 35000,
  "initializer_range": 0.02,
  "layer_norm_epsilon": 1e-05,
  "model_type": "gpt2",
  "n_ctx": 256,
  "n_embd": 768,
  "n_head": 12,
  "n_inner": null,
  "n_layer": 12,
  "n_positions": 1024,
  "reorder_and_upcast_attn": false,
  "resid_pdrop": 0.1,
  "scale_attn_by_inverse_layer_idx": false,
  "scale_attn_weights": true,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
  "summary_type": "cls_index",
  "summary_use_proj": true,
  "task_specific_params": {
    "text-generation": {
      "do_sample": true,
      "max_length": 50
    }
  },
  "transformers_version": "4.21.3",
  "use_cache": true,
  "vocab_size": 35000
}

In [ ]:

# call Language Model Pipeline with config GPT-2

model = TFGPT2LMHeadModel(config=config)
model(model.dummy_inputs)  # Builds the model
model.summary()

Model: "tfgpt2lm_head_model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 transformer (TFGPT2MainLaye  multiple                 112722432 
 r)                                                              
                                                                 
Total params: 112,722,432
Trainable params: 112,722,432
Non-trainable params: 0
_________________________________________________________________


## Define TPU/GPU for Distibuted training

In [ ]:
#check gpu type
!nvidia-smi

Sun Sep 11 06:42:01 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   39C    P0    26W /  70W |   1528MiB / 15109MiB |      4%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
import tensorflow as tf

In [ ]:
try: # <= detect TPU 
    tpu = tf.distribute.cluster_resolver.TPUClusterResolver()
    print("Running on TPU ", tpu.cluster_spec().as_dict()["worker"])
    tf.config.experimental_connect_to_cluster(tpu)
    tf.tpu.experimental.initialize_tpu_system(tpu)
    strategy = tf.distribute.TPUStrategy(tpu)
except ValueError: # <= detect GPU/CPU
    print("Not connected to a TPU runtime. Using CPU/GPU strategy")
    strategy = tf.distribute.MirroredStrategy()

Not connected to a TPU runtime. Using CPU/GPU strategy


In [ ]:
print('Number of replicas:', strategy.num_replicas_in_sync)

Number of replicas: 1


## Define Optimizer 
AdamW Optimizer

In [ ]:
pip install tensorflow_addons

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.1 MB 18.2 MB/s 


In [ ]:

# config optimizer & learning scheduler

# Number of training samples.
n_data_train = len(tokenized_datasets["train"])

# Total epochs to train.
epochs = 5

# Base learning rate after warmup.   
init_lr = 1e-4
min_lr = 1e-5
num_train_steps = n_data_train * epochs

# Compute the number of warmup batches.  
warmup_steps = 700

# weight decay 
weight_decay = 1e-2

In [ ]:
from transformers import create_optimizer # default AdamW

In [ ]:
# default AdamW
# for GPU
optimizer, schedule = create_optimizer(
    init_lr=init_lr,
    num_warmup_steps=warmup_steps,
    num_train_steps=num_train_steps,
    weight_decay_rate=weight_decay,
)

In [ ]:
import tensorflow_addons as tfa

In [ ]:
ADABELIEF = tfa.optimizers.AdaBelief(learning_rate = init_lr,
                                     #min_lr = min_lr,
                                     total_steps = num_train_steps, 
                                     weight_decay = weight_decay)

In [ ]:

# learning rate schedule if use TPU

lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(
    init_lr, decay_steps=100000, decay_rate=0.96, staircase=True
)

In [ ]:

# optimizer if use TPU

from tensorflow_addons.optimizers import AdamW

AdamW = AdamW(learning_rate =lr_schedule, weight_decay=weight_decay)

## Compile Model

Compile model with mixed mixed-precision float16 and Distributed GPU

In [ ]:
# Train in mixed-precision float16, change to float32 for better 
tf.keras.mixed_precision.set_global_policy("mixed_float16")

In [ ]:

# masukan lagi, untuk distributed training GPU nya 


with strategy.scope(): 
    model = TFGPT2LMHeadModel(config=config)
    model.compile(optimizer = optimizer)

No loss specified in compile() - the model's internal loss computation will be used as the loss. Don't panic - this is a common way to train TensorFlow models in Transformers! To disable this behaviour please pass a loss argument, or explicitly pass `loss=None` if you do not want your model to compute a loss.


## Fit & Push

Define Callbacks 
PushToHub for push model to hub 
& Tensorboard for ML Tracking

In [ ]:
#login dengan User Access Tokens 
# login untuk memasukan model ke hub 

from huggingface_hub import notebook_login

notebook_login()

Login successful
Your token has been saved to /root/.huggingface/token
Authenticated through git-credential store but this isn't the helper defined on your machine.
You might have to re-authenticate when pushing to the Hugging Face Hub. Run the following command in your terminal in case you want to set this credential helper as the default

git config --global credential.helper store


In [ ]:
from transformers.keras_callbacks import PushToHubCallback
from tensorflow.keras.callbacks import TensorBoard

In [ ]:
from transformers import set_seed # set seed 42

In [ ]:
# latih 
# callbacks

push_hub = PushToHubCallback(output_dir="gpt2-ft-id-puisi", tokenizer=tokenizer)
tensorboard_callback = TensorBoard(log_dir='logs')

callbacks = [push_hub, 
             tensorboard_callback]

set_seed(42)
model.fit(tf_train_dataset, validation_data=tf_eval_dataset, callbacks=callbacks, epochs = epochs) #jit_compile=True)

Cloning https://huggingface.co/Sultannn/gpt2-ft-id-puisi into local empty directory.


Download file tf_model.h5:   0%|          | 403/430M [00:00<?, ?B/s]

Clean file tf_model.h5:   0%|          | 1.00k/430M [00:00<?, ?B/s]

Epoch 1/5
913/913 [==============================] - 286s 278ms/step - loss: 7.3561 - val_loss: 6.5449
Epoch 2/5
913/913 [==============================] - 231s 253ms/step - loss: 6.2176 - val_loss: 6.1573
Epoch 3/5
913/913 [==============================] - 232s 254ms/step - loss: 5.8533 - val_loss: 6.0014
Epoch 4/5
913/913 [==============================] - 231s 253ms/step - loss: 5.5955 - val_loss: 5.8798
Epoch 5/5
913/913 [==============================] - 231s 253ms/step - loss: 5.3628 - val_loss: 5.8179


Several commits (2) will be pushed upstream.
The progress bars may be unreliable.


Upload file tf_model.h5:   0%|          | 3.34k/430M [00:00<?, ?B/s]

Upload file logs/validation/events.out.tfevents.1662879217.646579fd294b.70.1.v2: 100%|##########| 818/818 [00:…

Upload file logs/train/events.out.tfevents.1662878964.646579fd294b.70.0.v2:   0%|          | 3.34k/3.05M [00:0…

remote: Scanning LFS files for validity, may be slow...        
remote: LFS file scan complete.        
To https://huggingface.co/Sultannn/gpt2-ft-id-puisi
   a1d6f73..d4df38f  main -> main

remote: LFS file scan complete.        
To https://huggingface.co/Sultannn/gpt2-ft-id-puisi
   a1d6f73..d4df38f  main -> main



## Coba Model 

In [ ]:
!pip install transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 4.7 MB 32.8 MB/s 
     |████████████████████████████████| 120 kB 62.5 MB/s 
     |████████████████████████████████| 6.6 MB 48.8 MB/s 


In [21]:
# ambil pre trained model nya 
from transformers import pipeline, AutoTokenizer, TFGPT2LMHeadModel

model_ku = TFGPT2LMHeadModel.from_pretrained("Sultannn/gpt2-ft-id-puisi")
token_ku = AutoTokenizer.from_pretrained("Sultannn/gpt2-ft-id-puisi")\
# define autoregresive model
pipe = pipeline(
    "text-generation", model=model_ku, tokenizer=token_ku, device=0, pad_token_id = token_ku.eos_token_id)# to GPU

All model checkpoint layers were used when initializing TFGPT2LMHeadModel.

All the layers of TFGPT2LMHeadModel were initialized from the model checkpoint at Sultannn/gpt2-ft-id-puisi.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFGPT2LMHeadModel for predictions without further training.


In [ ]:
pipe # check 

In [22]:
# buat prompt atau text OR MAKE A INPUT AND THEN ENCODE TO TOKEN 

text = token_ku.encode("SETAN",add_special_tokens=True, return_tensors="tf") 
text

<tf.Tensor: shape=(1, 2), dtype=int32, numpy=array([[1640, 2790]], dtype=int32)>

In [23]:
# GENERATE MODEL 

output_sequences = model_ku.generate(

        # param penting
        input_ids = text, # raw token 
        max_length= 120 + len(text), # max token to generate
        do_sample=True,
       
        #length_penalty=2.0,  #Atur ke nilai <1.0 untuk menghasilkan urutan yang lebih pendek, ke nilai > 1.0 untuk menghasilkan urutan yang lebih panjang)    

        # pencarian modern          
        top_k=50, # ambil top kata dengan probability tertinggi / kata yang paling mungkin
        top_p=0.95, # ambil kata dan jumlah kan probalitiy nya sesuai yang di definisikan

        # no_repeat_ngram_size=2 , # agar tidak ada 2 gram/kata yang muncul dua kali:
        # temperature=1.0, # untuk mengatur probability next word 

        # trick / metode pencarian tradisional
        # num_beams=3, # Pencarian mengurangi risiko hilangnya urutan kata probabilitas tinggi yang tersembunyi dengan menjaga hipotesis yang paling mungkin pada setiap langkah waktu dan akhirnya memilih hipotesis yang memiliki probabilitas tertinggi secara keseluruhan 
        # early_stopping=True, # gunakan jika pakai num_beams > 1 
        # repetition_penalty=1.0, # mencegah kata pengulangan

        # jika ingin lebih dari 1 output
        #num_return_sequences=4,# num_return_sequences <= num_beams! jumlah balok skor tertinggi yang harus dikembalikan ? jumlah sample yang ingin dikeluarkan sesuai yang didefinisikan
    )

The attention mask and the pad token id were not set. As a consequence, you may observe unexpected behavior. Please pass your input's `attention_mask` to obtain reliable results.
Setting `pad_token_id` to 35000 (first `eos_token_id`) to generate sequence


In [ ]:
output_sequences # TOKEN OUTPUT


<tf.Tensor: shape=(1, 121), dtype=int32, numpy=
array([[ 6353, 27634,  2032,   262,  2521,  1305,  2065,  3768,   262,
        29493,   396,   470,  2837,   958,   262,  3471,  2988,   916,
         1467,  3377,   262, 10687,   810,   856,   729,  3131,   320,
          397,   670,   262,   948,  2443,  1244,  1436,   363,   934,
          627,   262,   543,  5804,   624,  4356,  3042,   262,  5455,
          376,  1066,  1309,   262,   817,  3292,  1898,   408,   348,
          470,  1421,    18,   322,  2701,   294,   524,   262,  1395,
         6439,   262,   779,   476,   408,  1752,   262,  1173,   768,
          795,   849,   262,   452,   765,   262, 10704,  1083,   624,
          408,   262,  1569,   408,  1752,   322,  1365,  1198,   578,
         1132,  7968,   261,  1184,   262,   452, 11477,    17,  8549,
          524,  2961,   262, 15326,   571,   262,   432,   723,   624,
          946,  5161,   354,  1063,   262,   874,  2846,   363,   262,
          432,   476,   841, 

In [ ]:
token_ku.decode(output_sequences[0], clean_up_tokenization_spaces=True) # DECODE TOKEN 

'SETANAHNYA \n Di saat ku tak bisa ku hanya sekedar rasa \n Dan aku punya harapan \n Aku ingin ku dan ku \n Aku pun tak lagi bisa \n Tapi itu aku \n Ketika itu yang sedang tertawa \n Yang lebih lain \n Ku tak ingin di hatiku \n Ku tak mampu bersama mu \n  \n Di setiap hati ku terima semua \n Apa satu semua orang yang lain \n Karena aku selalu ada di masa dalam hatiku \n Karena ku berharap seperti hal terindah dalam hidup ku \n Dan banyak cerita ku \n Dan bukan orang lain dengan mu \n Yang aku ingin ku \n Di setiap kali aku mencintai semua ini ku \n Ku akan pernah berhenti'

## Deploy model with Gradio

In [ ]:
pip install gradio

In [ ]:
pip install transformers

In [31]:
%%writefile app.py


#GPT2 FINE TUNE

# library 
import gradio as gr
import tensorflow as tf  
from transformers import pipeline, AutoTokenizer, TFGPT2LMHeadModel


# function to run
def run_model(input_text, 
              max_length,            
              length_penalty):

    #MBART Transformer 
    model_gpt2 = TFGPT2LMHeadModel.from_pretrained("Sultannn/gpt2-ft-id-puisi")
    token_gpt2 = AutoTokenizer.from_pretrained("Sultannn/gpt2-ft-id-puisi")

    # preprocessing text input
    input_text = str(input_text)
    input_text = ' '.join(input_text.split()).upper() # hapus white space dan ubah judul kata ke huruf besar

    #encode input to vector
    text_prompt = token_gpt2.encode(input_text,add_special_tokens=True, return_tensors="tf") 

        
    #generate input
    summary_ids = model_gpt2.generate(text_prompt, # raw token 
                                    # param penting
                                    max_length = max_length + len(input_text), # max token to generate
                                    do_sample = True, # to sampling text 
                                                                        
                                    length_penalty = length_penalty,  #Atur ke nilai <1.0 untuk menghasilkan urutan yang lebih pendek, ke nilai > 1.0 untuk menghasilkan urutan yang lebih panjang)    

                                    # pencarian modern          
                                    top_k = 50, # ambil top kata dengan probability tertinggi / kata yang paling mungkin
                                    top_p = 0.95, # ambil kata dan jumlah kan probalitiy nya sesuai yang di definisikan

                                    # no_repeat_ngram_size=2 , # agar tidak ada 2 gram/kata yang muncul dua kali:
                                    # temperature=1.0, # untuk mengatur probability next word 

                                    # trick / metode pencarian tradisional
                                    # num_beams=3, # Pencarian mengurangi risiko hilangnya urutan kata probabilitas tinggi yang tersembunyi dengan menjaga hipotesis yang paling mungkin pada setiap langkah waktu dan akhirnya memilih hipotesis yang memiliki probabilitas tertinggi secara keseluruhan 
                                    # early_stopping=True, # gunakan jika pakai num_beams > 1 
                                    # repetition_penalty=1.0, # mencegah kata pengulangan

                                    # jika ingin lebih dari 1 output
                                    # num_return_sequences=3,# num_return_sequences <= num_beams! jumlah balok skor tertinggi yang harus dikembalikan ? jumlah sample yang ingin dikeluarkan sesuai yang didefinisikan
                                    )                                                                       
                                        

    #decode output to text
    output = token_gpt2.decode(summary_ids[0], clean_up_tokenization_spaces=False) 

    return output # get output to str
                             
# end 

#example 
contoh = [["TAMPAN"],["TIDAK JELAS"]]
          
#judul
title = "Generate Puisi Indonesia"

#deskripsi
description = "Demo for Puisi Generator ID. Models are GPT-2"           

#footer            
article = "<p style='text-align: center'><a href='https://github.com/sultanbst123/Text_summarization-id2id' target='_blank'><u>Untuk penjelasan lihat di repo ku</u> 😁</a></p>"

#run gradio
gr.Interface(
    fn=run_model,
    #input text
    inputs=[
        gr.inputs.Textbox(
            lines=2,
            placeholder="Ketik disini...", 
            label="Text",
        ),
        #fine tune

        #max length
        gr.inputs.Slider(
           minimum=100,
           maximum=150,  
           step=5,
           default=100, 
           label="Max Length(panjang maksimum urutan)",
       ),
        #length_penalty
        gr.inputs.Slider(
           minimum=1,
           maximum=3,  
           step=1,
           default=1,
           label="Length Penalty(pilih 1 jika ingin yang panjang)",
       ),        
    ],
    #output text
    outputs=
    gr.outputs.Textbox(       
            label="Output text", 
    ),
    title=title,
    description=description,
    article=article,
    examples=contoh).launch(debug = True)



## GOOD LUCK 

Writing app.py


## SAVE TO OTHER FILE

In [32]:
!cp "/content/app.py" "/content/sample_data/GPT2 ID"

In [34]:
pip install pipreqs

In [35]:
!pipreqs "/content/sample_data/GPT2 ID" # MAKE requirements TXT 

INFO: Successfully saved requirements file in /content/sample_data/GPT2 ID/requirements.txt
